# Generated by Django 3.2.3 on 2023-08-22 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingradientrecipe_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingradientrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
    ]
