# Generated by Django 3.2.3 on 2023-08-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingradientrecipe_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingradientrecipe',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
