# Generated by Django 3.2.3 on 2023-08-23 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_remove_recipe_ingredients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngredientRecipe',
        ),
    ]
