# Generated by Django 3.2.3 on 2023-08-27 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20230825_2326'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'measurement_unit')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'color', 'slug')},
        ),
    ]
