# Generated by Django 3.2.3 on 2023-08-14 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Follow'},
        ),
    ]
