# Generated by Django 3.2.3 on 2023-08-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_follow_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
