# Generated by Django 3.2.3 on 2023-08-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20230824_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=50, null=True),
        ),
    ]
