# Generated by Django 3.2.3 on 2023-08-21 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagRecipe',
        ),
    ]
