# Generated by Django 3.2.3 on 2023-08-21 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230821_2018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagRecipe',
            new_name='TagsRecipe',
        ),
    ]
